#!/bin/bash

if [[ $# < 3 ]]; then
  echo "Usage: ${0##*/} [sbt|maven] [local|cdh] <name>" >&2
fi

type=$1
version=$2
name=$3

case ${version} in
  local)
	sparkversion="0.9.0"
	;;
  cdh)
	sparkversion="0.9.0-cdh5.0.0"
	;;
  *)
	echo "Unrecognised version: ${version}" >&2
esac

# Make directory
if mkdir $3; then
  mkdir -p ${name}/src/main/scala
  if [[ ${type} == "sbt" ]]; then
    cat <<-EOF > ${name}/build.sbt 
	name := "${name}"

	version := "1.0"

	scalaVersion := "2.10.3"

	libraryDependencies += "org.apache.spark" % "spark-core_2.10" % "${sparkversion}"

	resolvers ++= Seq(
	  "Cloudera Repository" at "https://repository.cloudera.com/artifactory/cloudera-repos/",
	  "Akka Repository" at "http://repo.akka.io/releases/"
	)
	EOF
  elif [[ ${type} == "maven" ]]; then
    cat <<-EOF > ${name}/pom.xml 
	<project>
	  <groupId>${name}</groupId>
	  <artifactId>${name}</artifactId>
	  <modelVersion>4.0.0</modelVersion>
	  <name>Simple Project</name>
	  <packaging>jar</packaging>
	  <version>1.0</version>
	  <repositories>
	    <repository>
	      <id>Akka repository</id>
	      <url>http://repo.akka.io/releases</url>
	    </repository>
	    <repository>
	      <id>Cloudera repository</id>
	      <url>https://repository.cloudera.com/artifactory/cloudera-repos</url>
	    </repository>
	  </repositories>
	  <pluginRepositories>
	    <pluginRepository>
	      <id>scala-tools.org</id>
	      <name>Scala-tools Maven2 Repository</name>
	      <url>http://scala-tools.org/repo-releases</url>
	    </pluginRepository>
	  </pluginRepositories>
	  <dependencies>
	    <dependency>
	      <groupId>org.scala-lang</groupId>
	      <artifactId>scala-library</artifactId>
	      <version>2.10.3</version>
	    </dependency>
	    <dependency> <!-- Spark dependency -->
	      <groupId>org.apache.spark</groupId>
	      <artifactId>spark-core_2.10</artifactId>
	      <version>${sparkversion}</version>
	    </dependency>
	  </dependencies>
	  <plugins>
	    <plugin>
	      <groupId>org.scala-tools</groupId>
	      <artifactId>maven-scala-plugin</artifactId>
	      <executions>
	        <execution>
	          <goals>
	            <goal>compile</goal>
	            <goal>testCompile</goal>
	          </goals>
	        </execution>
	      </executions>
	    </plugin>
	  </plugins>
	</project>
	EOF
  fi
fi

